### ISSUE TITLE
Basic Tutorial

### ISSUE THREAD

**Issue by Imaginativeone** [ModusCreateOrg/ionic-vue#100]
Is there a resource that shows the steps for creating the basic Modus/Ionic app? I’m having trouble getting the app to work with the GitHub instructions.

**Comment by michaeltintiuc** [comment]
Hey @Imaginativeone sorry for not replying earlier, here's a set of examples that should get you going: https://github.com/ModusCreateOrg/ionic-vue-examples/
If you don't mind, let me know what wasn't working for you from README, I'll make sure to fix it otherwise feel free to submit a PR

**Comment by Imaginativeone** [comment]
@michaeltintiuc I can't thank you enough for responding to my post. When I follow up, is it okay if I post video? Alternatively, I can use pictures.

**Comment by michaeltintiuc** [comment]
@Imaginativeone either is fine, whichever works best for you in getting your point across.
