### ISSUE TITLE
Nuxt support in universal mode (SSRed Web Components)

### ISSUE THREAD

**Issue by 4aficiona2** [ModusCreateOrg/ionic-vue#101]
I'm trying to figure out if it is somehow possible to SSR Ionic Vue Router links in Nuxt? I'm aiming for a server side rendered navigation based on Web Components (generated with Stencil for the dist/hydrate output target, deployed through npm, included / rendered within Nuxt e.g. like [this](https://github.com/Gomah/nuxt-stencil) implementation).

Could this be achieved with ionic-vue? Or could the Nuxt router be extended in a similar way like the Vue router so we could achieve a Nuxt Ionic Router?

**Comment by grgur** [comment]
My $0.02

Web Components rely on browser-specific APIs. In Server Side Rendering, these APIs can be used in a headless browser, but that comes at a major expense. Especially when there's lots of traffic. I'm not sure a business can justify that expense when Web Components are, in fact, very light. 

Representing Shadow DOM as plain HTML is hard. Hydration would make it even harder. To make things worst, server side rendering engine may be entirely different than the client's browser implementation, which could further complicate things.

I believe the nuxt-stencil implementation you mentioned above suffers from similar hydration issues (node mismatch). 

With all that said, Web Components are definitely not as "flexible" as Vue or React or Angular components when we need SSR. 

I feel that any implementation of SSR would be quasi for Web Components in general, including Ionic and Stencil.  I'm not sure I'd recommend that in production.
