### ISSUE TITLE
Header/toolbar height on iPhone X and iPhone 11

### ISSUE THREAD

**Issue by RobinHavre** [ModusCreateOrg/ionic-vue#105]
When building for iOs using Capacitor or Cordova, the header/toolbar has the wrong height, and is thus partially hidden behind the phone besel and the statusbar.

![image](https://user-images.githubusercontent.com/3342645/74236480-959a1380-4cd1-11ea-80cd-339039621ba9.png)

**Comment by michaeltintiuc** [comment]
It's definitely an issue with the core Ionic library, depends on the version you're pulling in

**Comment by michaeltintiuc** [comment]
Try with Ionic 5, update to ionic-vue 1.3.5 though

**Comment by RobinHavre** [comment]
I get the same result also using @ionic/core 5.0.7 and @modus/ionic-vue 1.3.6. 

My hack has been to add ``padding-top: 40px;`` to the ``header-ios`` class, but with the new translucent toolbar this is no longer sufficient.

**Comment by michaeltintiuc** [comment]
I know for fact that ionic-vue does not mess in any way with Ionic styles, I wonder if you can reproduce this in React or Angular versions of Ionic, have you checked for similar issues in ionic repo?

**Comment by RobinHavre** [comment]
I'm using Ionic/Angular for most projects, and have no issues with this there.

**Comment by michaeltintiuc** [comment]
@RobinHavre could you share your setup? I could give it a try, @zwacky have you had any similar issues?

**Comment by zwacky** [comment]
Hey there, sorry the only project I worked on is currently not running ionic 5 :( and for ionic 4 there are no problems.

> "@ionic/core": "4.11.4",
> "@modus/ionic-vue": "1.3.3",

**Comment by RobinHavre** [comment]
Below you see my setup. Everything works Vue- and Ionic-wise, but when I run this as a Cordova or Capacitor app in the XCode simulator for iPhone X or iPhone 11, the navbar does not account for the phone besel, as in the screenshot above. 

package.json
```json
{
  "name": "test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "@capacitor/android": "^1.3.0",
    "@capacitor/cli": "^2.0.1",
    "@capacitor/core": "^2.0.1",
    "@ionic/core": "^5.0.7",
    "@ionic/pwa-elements": "^1.5.2",
    "@ionic/vue": "0.0.9",
    "@modus/ionic-vue": "^1.3.6",
    "axios": "^0.19.0",
    "monaco-editor": "^0.20.0",
    "monaco-editor-vue": "^1.0.9",
    "monaco-editor-webpack-plugin": "^1.8.2",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@capacitor/ios": "^2.0.1",
    "@vue/cli-service": "^4.0.0",
    "vue-template-compiler": "^2.6.10"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ]
}
```
main.js
```javascript
import Vue from 'vue';
import App from './App.vue';
import store from './store';

import Ionic, { IonicVueRouter } from '@modus/ionic-vue'

import router from './router';

import '@ionic/core/css/ionic.bundle.css'

import { defineCustomElements } from '@ionic/pwa-elements/loader';
defineCustomElements(window);

Vue.use(Ionic);
Vue.config.productionTip = false;

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app');
```
App.vue
```html
<template>
  <div id="app">
    <ion-app>
      <ion-vue-router />
    </ion-app>
  </div>
</template>

<style>

body{
  padding-top: constant(safe-area-inset-top);
  padding-top: env(safe-area-inset-top);
}
#app {
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  /* text-align: center; */
  color: #2c3e50;
}
</style>
```
Home.vue
```html
<template>
<div class="ion-page">
  <ion-header>
    <ion-toolbar>
      <ion-title>Header</ion-title>
    </ion-toolbar>
  </ion-header>
  <ion-content class="ion-padding">  
    Content here
  </ion-content>
</div>
</template>

<script>
</script>
```

**Comment by michaeltintiuc** [comment]
what about an actual device? could it be a simulator issue? ionic/vue doesn't really mess with anything in terms of styling and unfortunately for this situation I don't own any apple devices :(
