### ISSUE TITLE
keepAlive does not work continuously

### ISSUE THREAD

**Issue by midoushitongtong** [ModusCreateOrg/ionic-vue#106]
![C](https://user-images.githubusercontent.com/21253535/76729119-66286c00-6793-11ea-8f22-a27a3c5b48ee.gif)

**Comment by michaeltintiuc** [comment]
I'd be interested in seeing your code, haven't seen this in a while. I don't think this happens in `ionic-vue-examples`

**Comment by midoushitongtong** [comment]
> I'd be interested in seeing your code, haven't seen this in a while. I don't think this happens in `ionic-vue-examples`

codesandbox url [https://codesandbox.io/s/snowy-hooks-dkui7](https://codesandbox.io/s/snowy-hooks-dkui7)
Could it be that my usage is incorrect?

**Comment by michaeltintiuc** [comment]
No, it's not you, I could reproduce the issue, looks like it's something new, looking into it, thanks!

**Comment by michaeltintiuc** [comment]
OK, found the issue to be `keep-alive` itself and how newer versions of ionic are hiding the "leaving element":
1. When you transition for the first time, the entering element (page B) is set to a visible state and higher z-index
2. When you go back, page B becomes a leaving element and is being hidden with `display: none` style attr.
3. When you want to go to page B again, keep-alive restores it's previous state of a "leaving element" with it's display set to none.

Will implement a fix and release a new version ASAP, thanks for reporting this.

**Comment by michaeltintiuc** [comment]
Check version 1.3.6 @midoushitongtong
