### ISSUE TITLE
Inputs don't blur when making swipe gesture

### ISSUE THREAD

**Issue by majormarquis** [ModusCreateOrg/ionic-vue#127]
Hello, I noticed that input fields are still in focus when making gestures such as open/close menu swipe gesture, swipe-to-close modal gesture. The keyboard is still taking close to half of the screen which seems a bit bad for UX.

Example video: 
In this case I try to close a modal using the swipe-to-close gesture. As soon as I start the gesture I'd expect that the input field blurs, but it doesn't meaning the keyboard's still active.

Expectation: The input field should blur as soon as I start making the gesture (hence hiding the keyboard).

![ezgif-5-f7689549f774](https://user-images.githubusercontent.com/6692969/84452965-2f0d0e00-ac4f-11ea-9bed-51a525834eb8.gif)

A feedback would be much appreciated! Thanks :)

**Comment by michaeltintiuc** [comment]
Thanks for the issue, have you tested this behavior with Angular or React versions of Ionic. ionic-vue is does not handle any such things and it seems to me like it could be an issue on ionic's side. You should however be able to hook into the modal's dismiss event to blur the input

**Comment by michaeltintiuc** [comment]
Please reopen if/when you'll have more information to work with
