### ISSUE TITLE
Force mode to ios

### ISSUE THREAD

**Issue by jakubkoje** [ModusCreateOrg/ionic-vue#129]
Hey, I noticed that when I try to force Ionic to use ios mode on browser/android, it doesn't change to ios. 
I tried 2 different installations, both with no luck. 
`Vue.use(Ionic, { mode: 'ios' }); /
Ionic.install(Vue, { mode: 'ios' });`

On @ionic/vue it is working. 
Thanks for help.

**Comment by michaeltintiuc** [comment]
Thanks for the issue @jakubkoje working on a fix

**Comment by michaeltintiuc** [comment]
@jakubkoje for v2 try `1.3.9` and for v3 `3.0.0-alpha.5`

**Comment by jakubkoje** [comment]
Wow, that was fast. It's now working. Thanks.
