### ISSUE TITLE
Unable to get value from IonRadioGroup

### ISSUE THREAD

**Issue by a-Leong** [ModusCreateOrg/ionic-vue#145]
I'm unable to get data binding working correctly for IonRadioGroup: [example](https://github.com/a-Leong/ionic-vue-3-example).

The above example takes approach outlined in https://github.com/ModusCreateOrg/ionic-vue/issues/51:
```vue
<IonRadioGroup :value="foo" @ionChange="foo = $event.target.value">...</IonRadioGroup>
```
however the value of property foo does not change. Also tried:
```vue
<IonRadioGroup :value="foo" v-on:ionChange="foo = $event.target.value">...</IonRadioGroup>
```
and
```vue
<IonRadioGroup v-model="foo">...</IonRadioGroup>
```

**Comment by michaeltintiuc** [comment]
Hey @a-Leong , thanks for creating the issue. I've just release 3.0.0-alpha.15 and it should now be fixed, reopen the issue if anything goes wrong.
