### ISSUE TITLE
can't use @modus/ionic-vue together with strict: true tsconfig option

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#34]
Hey all

When I try importing `@modus/ionic-vue` with `"strict": true` enabled in my tsconfig.json, it will throw the following error.

```
[ts]
Could not find a declaration file for module '@modus/ionic-vue'. '…/node_modules/@modus/ionic-vue/dist/ionic-vue.common.js' implicitly has an 'any' type.
```

P.s. thx for initiative in creating the vue bindings 👍

**Comment by grgur** [comment]
@zwacky did you try something like `import * as ionicVue from @modus/ionic-vue`?

We could also create an empty typings file and default the module to `any` type until we finish Typescript integration

**Comment by zwacky** [comment]
Yes, `import * as ionicVue from @modus/ionic-vue` also results in the same error message I posted above.

I think the `any` default approach you suggested sounds like a good solution for now.

**Comment by michaeltintiuc** [comment]
@zwacky this could prove to be helpful with less code: https://stackoverflow.com/questions/22842389/how-to-import-a-js-library-without-definition-file-in-typescript-file
