### ISSUE TITLE
Compatibility with cordova app

### ISSUE THREAD

**Issue by am** [ModusCreateOrg/ionic-vue#47]
The provided example app (Beep) is built using capacitor, like ionic 4 apps. My doubt is if cordova apps can take advantage of ionic-vue using a regular cordova build.

I've been playing around and I could somehow integrate with cordova, somethings fail, like tabs component don't render well, but I don't know if this is supported or if it is some problem that an app using capacitor won't have.

**Comment by michaeltintiuc** [comment]
I don't think capacitor/cordova are related to ionic-vue, the tabs component is still at an early stage, so it depends on how you implemented it, you can check [this example](https://github.com/ModusCreateOrg/ionic-vue/blob/master/cookbook/tabs.html) for a working demo. But there is work to be done to make it work with different options.

**Comment by am** [comment]
Hi @michaeltintiuc ,

Thanks for the prompt response. Good news that capacitor is out of the equation. Please bear with me since I'm trying to have a full picture of how this works. I've used the same setup options on the ionic 4 example in the docs (I've used devtools on the documentation page and hacked the html directly) then I've tried to use the same options the example application where I use ionic-vue, and that did not work. 
Without getting into specifics of what works what not, I don't see any reference in this repo of tabs component... so I assume it uses the one from ionic/core, how could it be that works differently?

**Comment by michaeltintiuc** [comment]
@am if you could share your usage of tabs I could take a look at it

**Comment by am** [comment]
@michaeltintiuc I was isolating the issue on codepen so I could share, here it goes:

ionic-vue:
https://codepen.io/a--m/pen/LgdqYY?editors=1010

ionic-js:
https://codepen.io/a--m/pen/mzxvWW?editors=1010

And the other case is editing the example on [ionic documentation](https://beta.ionicframework.com/docs/api/tabs/) since I cannot do a codepen here goes a snapshot:
![screen shot 2018-10-18 at 17 59 21](https://user-images.githubusercontent.com/33835/47167842-b467e000-d2ff-11e8-9be0-29c6ef3a67d5.png)

---

From what I can see both examples ionic-vue and ionic-js suffer from the same problem, the tabbar highlight does display (although the element exists in the doom it does not animate or get the proper width, if you check closely you can see it renders 1px width and 2px height, like a little dot on the left edge beneath the tabs).

That said, I think I could assume this is an ionic problem. I think being on beta is what it means, the documentation is at beta11 and I'm using beta13, mather of fact I used a different API to change the tabs, since the one in the documentation does not work anymore.

In beta11 docs used:
```js
<ion-tabs tabbar-highlight="true" tabbar-placement="top">
```
In beta13, in ionic-vue and ionic-js example use the one found in current master:
```js
<ion-tabbar placement="top" highlight="true"></ion-tabbar>
```
I'll check for ionic issues, maybe this is a known problem.

**Comment by michaeltintiuc** [comment]
This indeed seems to be an upstream issue, although it worked fine in Firefox for me.
Anyway tabs have a very limited support as there's still some ongoing work being done
