### ISSUE TITLE
How to dismiss a modal using the modalController

### ISSUE THREAD

**Issue by am** [ModusCreateOrg/ionic-vue#48]
Following the example found in [cookbook/ionic-controllers.html](https://github.com/ModusCreateOrg/ionic-vue/blob/master/cookbook/ionic-controllers.html#L82-L92):

```js
modal() {
  this.$ionic.modalController.create({
    component: {
      template: `
        <div>
          <ion-content padding>
            <h1>Howdy!</h1>
            <ion-button>Close</ion-button>
          </ion-content>
        </div>
      `,
    }
  }).then(m => m.present())
},
```

How could I bind the inner button to the `dismiss()` action?

**Comment by michaeltintiuc** [comment]
good point @am I'll update the docs shortly, you should be able to do this if there's only one modal
```js
      this.$ionic.modalController.dismiss()
```

If you have multiple you can either get them by ID, as per Ionic docs or store the returned value into a variable

**Comment by am** [comment]
That would be great @michaeltintiuc !

Diggging in ionic docs I'm not sure how does this blend with `ionic-vue`. In [Ionic docs](https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/usage/angular.md) I see:
```js
import { Component } from '@angular/core';
import { ModalController } from '@ionic/angular';
import { ModalPage } from '../modal/modal.page';
@Component({
  selector: 'modal-example',
  templateUrl: 'modal-example.html',
  styleUrls: ['./modal-example.css']
})
export class ModalExample {
  constructor(public modalController: ModalController) {}

  async presentModal() {
    const modal = await this.modalController.create({
      component: ModalPage,
      componentProps: { value: 123 }
    });
    return await modal.present();
  }
}
```

What is the `modal.page`? It leads to a dead link, so I cannot fully understand what file format is that. It would be good if we could set as component a `vue` file, I tried that first, but it didn't work. 
---
Back to the example provided, I've found a solution following what you said:
```js
modal() {
  this.$ionic.modalController.create({
    component: {
      template: `
        <div>
          <ion-content padding>
            <h1>Howdy!</h1>
            <ion-button @click="$ionic.modalController.dismiss()">close</ion-button>
          </ion-content>
        </div>
      `,
    }
  }).then(m => m.present())
},
```
Although this works I can see that will be easly unmanagable for more complex modal cases. As said if there is a way to use `.vue` files it would be great.

**Comment by michaeltintiuc** [comment]
There's no difference between using `.vue` files or plain JS, by docs I meant see the available methods for modal, they are all supported.

**Comment by michaeltintiuc** [comment]
`modal.page` is just the component they are showing, same as `component.template` in Vue, you can pass components to it as well

**Comment by am** [comment]
> you can pass components to it as well

You are right! I've must have done something wrong, since I've tried this before and did not work.

All clear now, moving on ;)

Thanks 👍
