### ISSUE TITLE
How to get value from ion-select component?

### ISSUE THREAD

**Issue by am** [ModusCreateOrg/ionic-vue#51]
I'm using `ion-select` component:

```vue
<ion-select :value="$i18n.locale" ok-text="Ok" cancel-text="Cancel">
  <ion-select-option v-for="language in languages" :value="language.locale">{{ language.label }}</ion-select-option>
</ion-select>
```
I need now to update/bind the value from the component width `$i18n.locale`. How can this achived?

**Comment by michaeltintiuc** [comment]
Please provide a full example @am that we can work with/test

**Comment by am** [comment]
Sure, I'll simplify then:

```vue
<ion-select value="foo" ok-text="Ok" cancel-text="Cancel">
  <ion-select-option value="foo">Foo</ion-select-option>
  <ion-select-option value="bar">Bar</ion-select-option>
</ion-select>
```
Consider the above component, how can the `value` be retrieved once it changes?

**Comment by michaeltintiuc** [comment]
Thanks @am what I meant a link to the repo or smth we can fiddle with, I will try to test myself as well

**Comment by am** [comment]
I'm currently testing this on a private repository. I thought at some point that would be nice to have a separate project that I could share but I have nothing right now. I'll take note and as soon as I can create this sandbox project.

**Comment by am** [comment]
Here it goes @michaeltintiuc, I think this is the simplest way to get there, it's a project you recognize 😉 and it will serve to exemplify the issue:

https://github.com/ModusCreateOrg/beep/compare/master...am:issues/ion-select

**Comment by am** [comment]
A similar case happens on the [toggle](https://beta.ionicframework.com/docs/api/toggle) component, where I don't know how to bind the component to the model, if you see the angular documentation this is done using `[(ngModel)]`:

```js
<ion-toggle [(ngModel)]="mushrooms"></ion-toggle>
```

This looks similar to what is done on Vue with [v-model](https://vuejs.org/v2/guide/forms.html). It would be nice to have something similar to this.

**Comment by am** [comment]
This is not working for me, I've tried using `@change` and it does not fire or change the value. Am I missing something?

**Comment by michaeltintiuc** [comment]
@am I believe it should've been `ionChange` event as per the [docs](https://github.com/ionic-team/ionic/tree/master/core/src/components/select#events)

**Comment by am** [comment]
This is exactly what I was missing, I can listen to the same events as in the docs using `@event`, great!

```js
<ion-select @ionChange="foo = event.target.value" :value="foo"/>
```

Thanks @michaeltintiuc

**Comment by matiasmenares** [comment]
it worked for me with $event

`<ion-select @ionChange="foo = $event.target.value" :value="foo"/>
`
