### ISSUE TITLE
doc: Show how to call Ionic methods and passing non-primitive data

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#53]
Hey there
We just had our Ionic Berlin Meetup where we talked about Ionic + Vue together (slides: https://docs.google.com/presentation/d/1VUN2C2nC2AApPDh_Jy_7MwYprWIFGI93gLvBre399l4/edit#slide=id.gc6fa3c898_0_0)

Two things:
1) How to pass data, especially non-primitive, to the Ionic Components
2) How to call an Ionic Component method

Both are answered briefly in the slides.
I could add a new cookbook for 2).

for 1) I would add a little section in README pointing out that binding attributes and properties are not the same (e.g. `:myProp="true"` is not the same as `:myProp.prop="true"`).

Tell me what you think, Cheers

**Comment by jongwon** [comment]
why not props?

**Comment by zwacky** [comment]
Just to clarify with a real example here.

This doesn't work, because it's bound to attribues:
```
<ion-slides :options="{ loop: true }">
…
</ion-slides>
```

This does work, because it's bound to properties and can be understood by web components:
```
<ion-slides :options.prop="{ loop: true }">
…
</ion-slides>
```

my earlier example with `:myProp.prop="true"` is not really helpful I saw as the web component does understand primitive types just fine as I understand.

**Comment by michaeltintiuc** [comment]
Sorry for not getting back to you on this for so long, even though I'm extremely happy with your work and believe this has it's place in the docs/tutorials section that we are working on, I'm closing this issue for now, but if you're open to collaboration we can work on that together in the near future
