### ISSUE TITLE
Normal page transitions on android are modal transitions

### ISSUE THREAD

**Issue by lassesteffen** [ModusCreateOrg/ionic-vue#54]
## Bug
The page transition on android is the transition for showing modals (it goes from bottom to top instead of right to left).

##  Reproduce
Download the beep sample app, serve the app and select an android device on google chrome.

**Comment by michaeltintiuc** [comment]
As per [Ionic Docs](https://beta.ionicframework.com/docs/api/nav/) this is correct behavior.

**Comment by lassesteffen** [comment]
Okey I see, doesn't seem to right too me that this is the default, but then I'll head over to the ionic repo. Thanks!
