### ISSUE TITLE
Keyboard overlays my focused ion-inputs

### ISSUE THREAD

**Issue by sneko** [ModusCreateOrg/ionic-vue#55]
Hi @michaeltintiuc,

First of all, thank you Modus Create team for your work on this project :) 

I'm wondering if you got issues with the keyboard on iOS? I mean, if a `ion-input` is at the bottom of the page, when I click on it the keyboard is overlaying the input 😢  ... but when putting a basic HTML `input` the keyboard "pushes" the page up to make visible both the keyboard and the input.

Did you got the same problem?

Thank you,

**Comment by michaeltintiuc** [comment]
Hi @sneko I'll give it a try, but ultimately this has to be an @ionic issue, this would require a test in Angular. I'll get back to you

**Comment by sneko** [comment]
@michaeltintiuc since the @ionic/vue package doesn't use latest Ionic core I had prefered to ask you first if you got troubles when developing for iOS.

Maybe you just used it for desktop web browsers?

Thanks,

**Comment by michaeltintiuc** [comment]
@sneko ionic-vue doesn't have a hard version dependency of ionic/core, you are free to install the latest one

**Comment by michaeltintiuc** [comment]
Closing as not related to ionic/vue specifically, please report to @ionic directly
