### ISSUE TITLE
Modal - Get props inside component

### ISSUE THREAD

**Issue by paulohenriqu** [ModusCreateOrg/ionic-vue#56]
Hi,
I’m using a modal and I need to pass some props to the component, so I tried this:
`this.$ionic.modalController
        .create({
          component: ModalSelectSearch,
           componentProps: { title: "Teste" }          
        })
        .then(m => m.present());`
But I can’t get the props in my component, i tried like that:
`export default {
  name: "ModalSelectSearch",
  props: ['title'],`
But it didn’t work.
How can I get the props passed using componentProps in my component?

Thanks.

**Comment by michaeltintiuc** [comment]
Hi @paulohenriqu, thanks for reaching out, the docs on the lib is something Modus Create and Ionic need to do more work on :)
TLDR; Here's how you'd pass props or data to components:
```js
                        this.$ionic.modalController.create({
                            component: {
                                props: ['foo'],
                                data() {
                                    return {
                                        bar: '',
                                    }
                                },
                                template: `<div>
                                    <ion-content padding>
                                        <p>foo is {{ foo }}</p>
                                        <p>bar is {{ bar }}</p>
                                    </ion-content>
                                </div>`,
                            },
                            componentProps: {
                                data: {
                                    bar: 'BAR!',
                                },
                                propsData: {
                                    foo: 'FOO!',
                                }
                            },
                        })
                        .then(m => m.present())
```

The long version is that whatever you pass to `componentProps` is passed to the [opts](https://vuejs.org/v2/api/#Options-Data) argument of the [Vue constructor](https://vuejs.org/v2/guide/instance.html). So this is fully driven by the Vue API and is not something any of us came up with out of the blue.

This is where Ionic v4 shines by providing a framework-agnostic API and the rest is delegated to libraries such as ionic-vue, which is [@ionic/vue](https://github.com/ionic-team/ionic/tree/master/vue/) btw.

Hope this helps.

**Comment by paulohenriqu** [comment]
It worked, thank you very much.
