### ISSUE TITLE
Returning data from modal

### ISSUE THREAD

**Issue by paulohenriqu** [ModusCreateOrg/ionic-vue#57]
Hi,

I'm trying to return data from a modal.

I'm creating the modal using the following code:

` this.$ionic.modalController
        .create({
          component: Modal
        })
        .then(m => {
         m.onDidDismiss().then(data=>{
          console.log(data);    
         });      
          m.present();                   
        });`

However, if I dismiss the modal like that:

` this.$ionic.modalController.dismiss({
        result: 10
      });`

My result is the following:

`{data: undefined, role: undefined}`

If I dismiss the modal using vanilla javascript like this:

` const modalController = document.querySelector("ion-modal-controller");
      modalController.dismiss({
        result: 10
      });`

I get de expected result:

`{
  "data": {
    "result": 10
  },
"role": undefined
}`

Is there any bug with the modalController or I'm not using the correct syntax to dismiss the modal?

Thanks.

**Comment by michaeltintiuc** [comment]
@paulohenriqu I'll be checking it out shortly and will get back to you on this.

**Comment by michaeltintiuc** [comment]
Thank @paulohenriqu , this is now fixed in the latest version
