### ISSUE TITLE
Cookbook example: Trying to get tabs working

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#62]
Hey there

I'm trying to get <ion-tabs> working in my apps, as a form of view cache mechanism to preserve scroll position etc, but currently I'm having problems finding where the problem lies in my app.

Naturally I copied the [cookbook example for tabs](https://github.com/ModusCreateOrg/ionic-vue/blob/master/cookbook/tabs.html) to check from square 1 but it shows up some errors which I'm unsure about.

```
ionic-vue.js:304 Uncaught TypeError: Cannot read property 'LIFECYCLE_WILL_ENTER' of null
    at ionic-vue.js:304
    at ionic-vue.js:10
    at ionic-vue.js:11
(anonymous) @ ionic-vue.js:304
(anonymous) @ ionic-vue.js:10
(anonymous) @ ionic-vue.js:11

Uncaught TypeError: IonicVue.IonicVueRouter is not a constructor
    at (index):68
(anonymous) @ (index):68
```

or here a jsbin link: https://jsbin.com/caqapaqahi/edit?html,console,output

Can you point me in the right direction to get the example working? 🙌

**Comment by michaeltintiuc** [comment]
Hey @zwacky thanks for reaching out, I will take a look at it, but I haven't looked at tabs for a while, the other issues ring some bells, try updating to latest version, there were a few fixes for that already ;)

**Comment by zwacky** [comment]
fyi I went ahead and took a starter project to get to this implementation #63

**Comment by michaeltintiuc** [comment]
I'll be closing this one in favour of #63 as well as due to the fact that the changes in the arch made by Ionic core team to ionic/vue no longer support the non JS module appraoch, thus the cookbooks are void.
