### ISSUE TITLE
Vue Ionic Tabs: Not working as Angular Tabs

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#63]
The tabs in ionic-vue keep recreating, not keeping their scroll position, etc. Whereas in ionic-angular the tabs only create their content once, even when switching back and forth within the tabs.

I went ahead and did a bare minimum implementation of the vue ionic tabs over here: https://github.com/zwacky/test-ionic-vue-tabs

May I have mis-implemented this somehow?

**Comment by michaeltintiuc** [comment]
This should probably the next example for ionic/vue as it's one of the most widely used components. I believe there is room for improvement but is vue specific, I'll check it out right away. Thanks for your contributions btw

**Comment by michaeltintiuc** [comment]
@zwacky do you have an example of Angular tabs?

A quick update, basic tabs work fine, those without a router, but that also means that if you have 10 tabs, all 10 components will be initialized, unless you lazy-load them.

If you'd want to have separate routes for each, well that is working too, but requires a bit more testing now and confirmation that upon switching of the tab the component that we don't want garbage-collected stays put.

Concerning scrolling, same, needs to be tested, but looks like the official [VueRouter is quite flexible](https://router.vuejs.org/guide/advanced/scroll-behavior.html)

**Comment by zwacky** [comment]
@michaeltintiuc I just created a tabs started via `ionic start myApp tabs` and checked if the components get re-initialized/retain their scroll position—which they do.

**Comment by michaeltintiuc** [comment]
Thanks, what I mean is that with basic tabs it's the same with Vue, but if you want dynamic components, which free up memory that's different.

**Comment by zwacky** [comment]
Yes, it is indeed about tabs **with** the routing. I tried it in the https://github.com/zwacky/test-ionic-vue-tabs repo.

Then I realized that ion-tabs and ion-tab is way more to it than I thought. [The ionic-angular bindings have a coupling to its navigation router](https://github.com/ionic-team/ionic/blob/6929bb817cff5e4ac3eb266e7aca45173c361789/angular/src/directives/navigation/ion-tabs.ts#L70-L81), which works well together. This is probably where ionic-vue also needs some glue code?

I'd be very happy to help and contribute in this matter, just want to first understand where the problem lies and what has to be done.

**Comment by michaeltintiuc** [comment]
@zwacky I've been hacking at this over the weekend and there are good and bad news.

_The good:_
Simple tabs are working just fine and component state is saved due to the fact that all tab content components are loaded at the same time. This is bad in terms of memory management and does not allow for proper routing

_The bad:_
After syncing with Ioinic devs it turned out tabs are not used as web-components in angular nor in react versions, so I'll start on creating vue-specific tab components to handle routing etc.

**Comment by michaeltintiuc** [comment]
That's right, I'm already working on it

**Comment by michaeltintiuc** [comment]
Fixed in v1.2.12 - closing
