### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by christianmagill** [ModusCreateOrg/ionic-vue#71]
Thanks for your work on this project! 

Is there any type of a roadmap that would give me an idea of how far a long the project is, what's missing, planned, etc.?

**Comment by michaeltintiuc** [comment]
Hey @christianmagill, that's a great suggestion, we've been neck deep in code so much that forgot about such obvious things, I'll setup a plan ASAP and update the README which should include finished, finished but requiring rework, in-progress and any wont-fix items.

**Comment by christianmagill** [comment]
Much thanks!
