### ISSUE TITLE
How to emit an event to modal Vue instance?

### ISSUE THREAD

**Issue by sneko** [ModusCreateOrg/ionic-vue#73]
Hi,

I'm creating a modal through the Ionic controller with VueDelegate but I'm not able to make an event reaching to the creator element...

I tried:
- this.$emit() and on the other side `.addEventListener(...)` since the returned value is an HTML element
- this.$parent.$emit() so that I can directly listen through `this.$on(...)` but the modal is not able to understand `this.$parent`since it was created with VueDelegate

Any idea how I could manage that without implementing a store? I also thought about the parameter `componentProps` but the `v-on:abc` will probably not work.

Thank you,

**Comment by michaeltintiuc** [comment]
Hey @sneko have a look at [this example](https://github.com/ModusCreateOrg/ionic-vue-examples/blob/master/src/views/Modal.vue)

The above illustrates 2 ways of achieving this:
- passing a method to modal props
- using events

The catch with events is that you have to set the parent manually:

```
          componentProps: {
            parent: this,
            ...
          }
```

Which means that you can then do stuff like `this.$parent.$emit('close', {})`

**Comment by sneko** [comment]
@michaeltintiuc I just tried the second solution your example but `this.$parent` is still undefined in the modal when clicking on a button.

I looked at https://github.com/ModusCreateOrg/ionic-vue-examples/blob/master/src/components/modal/index.vue and it seems I didn't miss something hmmm, any particular thing to do?

Here is how I create my modal:
```
      const modal = await modalController.create({
        component: AbcDefinition,
        componentProps: {
          parent: this,
        },
        delegate: this.$ionicVueDelegate,
      });
```

Thank you,

**Comment by sneko** [comment]
@michaeltintiuc I updated my local vue-delegate related files since you modified them during January, and it works :) 

It could be the line about binding lifecycle events...

Thank you very much!
