### ISSUE TITLE
Overrinding Ionic SCSS ?

### ISSUE THREAD

**Issue by arcaweb** [ModusCreateOrg/ionic-vue#74]
Hi,

In Ionic base, we can create a src/theme/variables.scss to override basic colors.

How can we do that with ionic-vue ? Should we use webpack to build it, and include it in ionic:build command ?

Best regards

**Comment by michaeltintiuc** [comment]
I'm not sure what you mean by ionic base and as far as I know ionic/core does not export any SCSS files at all. You can override CSS variables though:

```css
:root ion-back-button {
  --color: #FFF000;
}
```

**Comment by arcaweb** [comment]
Ok so I have to use webpack, because in native Ionic (with Angular), the build and serve do that job.

**Comment by michaeltintiuc** [comment]
I've just checked the Ionic/Angular conference app and don't see any SCSS being used, it's the compiled CSS that's being imported:
https://github.com/ionic-team/ionic-stencil-conference-app/blob/master/src/global.css

So the process should be identical, as I've said, if you've setup your project via `vue-cli` you don't need to do any extra work, just import your CSS.
