### ISSUE TITLE
Adding "@modus/ionic-vue" requires 'ionicons/icons'

### ISSUE THREAD

**Issue by edstevo** [ModusCreateOrg/ionic-vue#75]
Hi,

I tried to play around with this today as the traditional vue-router is giving me issues with things like split-pane...

Anyway - I can't use it as I'm getting the following message: 

./node_modules/@modus/ionic-vue/dist/ionic-vue.esm.js
Module not found: Error: Can't resolve 'ionicons/icons' in '/Users/edstevo/Sites/xxxx/xxxx/node_modules/@modus/ionic-vue/dist'

From what I can gather, 'ionicons/icons', is a private repo so you can't get this from npm separately.

Thanks

**Comment by michaeltintiuc** [comment]
First of all the ionic/vue router is just an extension of the official vue router, so if that one is giving you problems, it's highly unlikely that ionic/vue will fix anything for you.
Regarding the [ionicons](https://github.com/ionic-team/ionicons), it's open sourced.
Make sure you have the latest versions of both ionic-vue and @ionic/core.

I can't think of anything else that could be an issue other than the packages and the versions you're pulling in.

**Comment by michaeltintiuc** [comment]
I'd also recommend checking out [ionic-vue-examples](https://github.com/ModusCreateOrg/ionic-vue-examples/) and how it's setup

**Comment by edstevo** [comment]
Hi Michael,

The ionic-vue-examples works fine, so thanks for that.

Also managed to resolve the first problem - @modus/ionic-vue specifies that you should install ionicons/icons whereas the actual repo is just called "ionicons" on npm.  Hence why I was having issues.

Thanks for the tips.
