### ISSUE TITLE
Popover isn't positioned correctly when used with mode 'md'

### ISSUE THREAD

**Issue by zwacky** [ModusCreateOrg/ionic-vue#79]
Hey there,
when opening a popover with `mode: 'md'` it doesn't take into account the height of the event's clicked element for its position. Works correctly with `mode: 'ios'`.

Can be tried out here: https://github.com/ModusCreateOrg/ionic-vue-examples (when merged https://github.com/ModusCreateOrg/ionic-vue-examples/pull/2).

Cheers

**Comment by michaeltintiuc** [comment]
Thanks, ultimately this was an upstream issue, see this: https://github.com/ionic-team/ionic/issues/17427

Updating to latest @ionic/core fixes this, tested with 4.1.1
