### ISSUE TITLE
How much time will it take to publish stable release of @ionic/vue ? 

### ISSUE THREAD

**Issue by takielias** [ModusCreateOrg/ionic-vue#81]
I'm waiting for the stable release of @ionic/vue. I'm really excited. I know there is some limitation in @ionic/vue. How much time will it take to publish stable release without limitation?

**Comment by michaeltintiuc** [comment]
Hey @takielias, I can't speak for Ionic on this, all I know is that it's closing in to a beta release. The only differences between this package and Ionic's at this point is the router and ion-tabs support, the latter is pending a PR. I would suggest you ask them through their contact channels.
In relation to limitations, are there any in particular? I'm unaware of any blockers really as I've used @modus/ionic-vue for several projects some of which were close to production.

The only "limitation" and I can hardly call it such, is the lack of support of `v-model` which is just a shorthand for `:value="myVar" @someEvent="myVar = $event.target.value"`

**Comment by takielias** [comment]
@michaeltintiuc Thanks for your response.

**Comment by takielias** [comment]
@michaeltintiuc Thanks For your Response. There is another limitation That I found [https://github.com/ionic-team/ionic/tree/master/vue](https://github.com/ionic-team/ionic/tree/master/vue) here is: Stack navigation for deep transitions is under heavy development at this time. But I'm confused. Can I use it for production?

**Comment by michaeltintiuc** [comment]
@takielias I'm not sure what this really means, I myself haven't found any issues with navigation or transitions really. You'll have to play around with it and decide for yourself, our definitions of production ready could differ based on use cases.
