### ISSUE TITLE
Any plans to support `ion-virtual-scroll`?

### ISSUE THREAD

**Issue by randytarampi** [ModusCreateOrg/ionic-vue#85]
Didn't see this mentioned in #71, and I don't quite know if this is more appropriate here than at https://github.com/ionic-team/ionic, but it'd definitely be really nice to have.

**Comment by michaeltintiuc** [comment]
It would be best to reach out to the official repo, but from what I know, it will be supported, but it would reuse the best implementation for each framework.

**Comment by randytarampi** [comment]
Fair. Closing this and following up on the Ionic side with ionic-team/ionic#17887.

**Comment by grgur** [comment]
My $0.02 here: virtualization is easily solved with framework specific libraries that already exist for Vue. This probably shouldn’t be a focus for Ionic integration with other frameworks 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
