### ISSUE TITLE
Router transitions not working?

### ISSUE THREAD

**Issue by sneko** [ModusCreateOrg/ionic-vue#89]
Hi @michaeltintiuc ,

I just saw your PR on the Ionic repo (https://github.com/ionic-team/ionic/pull/17901) and followed the documentation on yours.

My main issue is that I don't see the transition between both elements. When looking at the DOM tree I see the previous and next pages lasting together, but the next page appears just when the previous one is deleted.

I'm using a basic:
```
  ion-app
    ion-vue-router
```

While using IonicVueRouter instead of VueRouter.

Any idea idea what could be the missing piece? I tried with Ionic 4.4.0 and 4.1.1, and also using the @ionic/vue 0.0.4

Thank you,

EDIT: do components being routed need a specific structure? `ion-content`? `ion-page`?

**Comment by michaeltintiuc** [comment]
Hey, sorry for the delayed reply, but I'd suggest looking into how [the examples repo](https://github.com/ModusCreateOrg/ionic-vue-examples) is setup for this or sharing your code
